# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-16 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_admins', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterModel',
        ),
    ]
