# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-16 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_admins', '0002_delete_registermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ddos_attacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.CharField(max_length=500)),
                ('result', models.CharField(max_length=500)),
            ],
        ),
    ]
