# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-16 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_admins', '0004_auto_20181116_1401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ddos_attacks',
        ),
    ]
